modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
[[mods]]
modId = "yaif"
version = "1.21.1-1.0.0"
displayName = "WhyAmIonFire NeoForge"
authors = [
    "Ellivers",
    "Tapio",
    "Rinko"
]
description = "Hides the obstructive fire overlay when it's not needed."